### ISSUE TITLE
Unsafe use of eval

### ISSUE THREAD

**Issue by cristianstaicu** [matthewkastor/modulify#2]
In file src/modulify.js, the following use of eval may be dangerous: 

``` js
modulify.utils.evaluator = function evaluator(src) {
    eval(src);
};
modulify.utils.getGlobals = function getGlobals(src) {
    'use strict';
    var original = Object.keys(global);
    modulify.utils.evaluator(src);
    var fin = Object.keys(global);
    var out = fin.filter(function (item) {
        return original.indexOf(item) === -1;
    });
    return out;
};
```

The transformed file may execute arbitrary commands. Please place the eval in a sandbox instead!

**Comment by matthewkastor** [comment]
That doesn't work. There really isn't a way around using eval like this for the purpose that this module is intended for. Your going to have to read the code that you want to convert, or trust the author not to do terrible things. Besides, if the pain JavaScript you're converting has anticipated node, and does terrible things, it's probably already a node module and you don't need this package!
